/* =============================================================================
 *  code_filelist.h
 * -----------------------------------------------------------------------------
 *  AUTO-GENERATED by tools\gen_filelist.ps1 -- DO NOT EDIT BY HAND.
 *
 *  It #includes every .c file found under code\, which is how new user
 *  source files get picked up automatically without editing any project.
 *
 *  Regenerate:  tools\gen_filelist.ps1   (or run setup.bat)
 * ========================================================================== */

#ifndef CODE_FILELIST_H
#define CODE_FILELIST_H

#include "../code/camera.c"
#include "../code/perspective.c"

#endif /* CODE_FILELIST_H */
