/* =============================================================================
 *  code_headerlist.h
 * -----------------------------------------------------------------------------
 *  AUTO-GENERATED by tools\gen_filelist.ps1 -- DO NOT EDIT BY HAND.
 *
 *  It #includes every .h file found under code\, so that the simulation
 *  environment can pick up user declarations WITHOUT hard-coding a file
 *  name. Renaming or deleting your own headers therefore never breaks the
 *  environment (see the README section on how the environment finds
 *  your code).
 *
 *  Each entry is guarded with __has_include, so a stale entry left over
 *  from a deleted file is harmless.
 *
 *  Regenerate:  tools\gen_filelist.ps1   (or run setup.bat)
 * ========================================================================== */

#ifndef CODE_HEADERLIST_H
#define CODE_HEADERLIST_H

/* Fallback for compilers without __has_include (very old ones).
 * Every real toolchain used here (GCC 10 / MSVC 2017+) has it. */
#ifndef __has_include
#  define __has_include(x) 0
#endif

#if __has_include("../code/camera.h")
#  include "../code/camera.h"
#endif
#if __has_include("../code/perspective.h")
#  include "../code/perspective.h"
#endif
#if __has_include("../code/scut_port.h")
#  include "../code/scut_port.h"
#endif

#endif /* CODE_HEADERLIST_H */
