# =============================================================================
#  gen_filelist.ps1 -- scan code\ and generate env\code_filelist.h
# -----------------------------------------------------------------------------
#  WHY:  convienient auto-inclusion. Every .c file under code\ is #included by
#        env\simu_env.c through the generated code_filelist.h, so you can add
#        new .c/.h files in code\ WITHOUT touching the VS / Dev-C++ project.
#
#  HOW:  env\simu_env.c contains:   #include "code_filelist.h"
#
#  USAGE: powershell -ExecutionPolicy Bypass -File tools\gen_filelist.ps1
#         (build_dev.bat / build_vs.bat / setup.bat all call this for you)
#
#  NOTE:  This script is deliberately ASCII-only. Windows PowerShell 5.1 reads
#         .ps1 files as ANSI unless they have a UTF-8 BOM, so non-ASCII text
#         here would corrupt the parser on Chinese-locale Windows.
# =============================================================================

$ErrorActionPreference = 'Stop'

$Root    = Split-Path -Parent $PSScriptRoot          # project root
$CodeDir = Join-Path $Root 'code'
$OutFile = Join-Path $Root 'env\code_filelist.h'
$EnvDir  = Join-Path $Root 'env'

if (-not (Test-Path $EnvDir)) {
    Write-Host "[gen_filelist] ERROR: env\ directory not found at $EnvDir" -ForegroundColor Red
    exit 1
}
if (-not (Test-Path $CodeDir)) {
    New-Item -ItemType Directory -Force -Path $CodeDir | Out-Null
}

# --- collect .c files under code\ (recursive; skip _*.c and *.tmp) ---
# Every .c under code\ ends up in the SAME compilation unit (via code_filelist.h),
# and sub-directories are supported: the generated #include keeps the
# sub-directory part of the path (e.g. code\algo\line.c -> "../code/algo/line.c").
# Using only the file NAME here would silently break sub-directories, because the
# scan is recursive but the emitted path would not be.
$cFiles = @()
$cFiles = @(Get-ChildItem -Path $CodeDir -Filter '*.c' -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notlike '_*' -and $_.Name -notlike '*.tmp' } |
            Sort-Object FullName)

# Relative path (from code\) with forward slashes, so it can be used verbatim
# inside an #include. #include wants '/' (or escaped '\\'), never a bare '\',
# because a backslash inside a string is an escape character.
function Get-RelPath([string]$full, [string]$baseDir) {
    $rel = $full.Substring($baseDir.Length).TrimStart('\', '/')
    return ($rel -replace '\\', '/')
}

# --- warn about duplicate content -------------------------------------------
# Every .c under code\ ends up in the SAME compilation unit, so two files that
# define the same functions/variables will fail to link with confusing
# "redefinition of ..." errors. A very common cause is a stray copy of an
# existing file (e.g. someone duplicates camera.c to keep a backup).
# Detect identical content here and report it clearly instead.
# NOTE: compare by RELATIVE path, not bare name -- with sub-directories two
# different files can share a name (code\a\util.c and code\b\util.c) and the
# report must say which one is which.
$dups = @{}
foreach ($f in $cFiles) {
    $hash = (Get-FileHash $f.FullName -Algorithm MD5).Hash
    $rel  = Get-RelPath $f.FullName $CodeDir
    if ($dups.ContainsKey($hash)) {
        $dups[$hash] += ,$rel
    } else {
        $dups[$hash] = @($rel)
    }
}
$hasDup = $false
foreach ($k in $dups.Keys) {
    if ($dups[$k].Count -gt 1) {
        if (-not $hasDup) {
            Write-Host ""
            Write-Host "[gen_filelist] WARNING: duplicate source files in code\" -ForegroundColor Red
            $hasDup = $true
        }
        Write-Host ("               {0}  <- these are identical" -f ($dups[$k] -join '  ==  ')) -ForegroundColor Red
    }
}
if ($hasDup) {
    Write-Host "               All .c under code\ share one compilation unit, so identical" -ForegroundColor Red
    Write-Host "               files will cause 'redefinition of ...' build errors." -ForegroundColor Red
    Write-Host "               Delete the copy you do not need, or rename it to _xxx.c to skip it." -ForegroundColor Red
    Write-Host ""
}

# --- build the generated header ---
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('/* =============================================================================')
$lines.Add(' *  code_filelist.h')
$lines.Add(' * -----------------------------------------------------------------------------')
$lines.Add(' *  AUTO-GENERATED by tools\gen_filelist.ps1 -- DO NOT EDIT BY HAND.')
$lines.Add(' *')
$lines.Add(' *  It #includes every .c file found under code\, which is how new user')
$lines.Add(' *  source files get picked up automatically without editing any project.')
$lines.Add(' *')
$lines.Add(' *  Regenerate:  tools\gen_filelist.ps1   (or run setup.bat)')
$lines.Add(' * ========================================================================== */')
$lines.Add('')
$lines.Add('#ifndef CODE_FILELIST_H')
$lines.Add('#define CODE_FILELIST_H')
$lines.Add('')

if ($cFiles.Count -eq 0) {
    $lines.Add('/* no .c files under code\ yet */')
    Write-Host "[gen_filelist] no .c files found under code\" -ForegroundColor Yellow
}
else {
    foreach ($f in $cFiles) {
        # path is relative to env\ (the directory containing this include),
        # and keeps any sub-directory part of the file's location under code\.
        $rel = Get-RelPath $f.FullName $CodeDir
        $lines.Add('#include "../code/' + $rel + '"')
        Write-Host ("[gen_filelist] collected: code\{0}" -f ($rel -replace '/', '\')) -ForegroundColor Green
    }
}

$lines.Add('')
$lines.Add('#endif /* CODE_FILELIST_H */')

# --- also collect .h files, for the *header* list ----------------------------
# WHY: the environment (env\disp_env.hpp) must not hard-code a user header name
# like "camera.h" -- renaming or deleting the example would then break the whole
# build, even though config.h promises "just rename your functions and you are
# done". C has no way to glob a directory (no wildcards in __has_include, no
# directory includes), so instead we GENERATE a header list the same way we
# generate the .c list, and let the environment include that.
$hFiles = @()
$hFiles = @(Get-ChildItem -Path $CodeDir -Filter '*.h' -Recurse -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -notlike '_*' -and $_.Name -notlike '*.tmp' } |
            Sort-Object FullName)

$hl = New-Object System.Collections.Generic.List[string]
$hl.Add('/* =============================================================================')
$hl.Add(' *  code_headerlist.h')
$hl.Add(' * -----------------------------------------------------------------------------')
$hl.Add(' *  AUTO-GENERATED by tools\gen_filelist.ps1 -- DO NOT EDIT BY HAND.')
$hl.Add(' *')
$hl.Add(' *  It #includes every .h file found under code\, so that the simulation')
$hl.Add(' *  environment can pick up user declarations WITHOUT hard-coding a file')
$hl.Add(' *  name. Renaming or deleting your own headers therefore never breaks the')
$hl.Add(' *  environment (see the README section on how the environment finds')
$hl.Add(' *  your code).')
$hl.Add(' *')
$hl.Add(' *  Each entry is guarded with __has_include, so a stale entry left over')
$hl.Add(' *  from a deleted file is harmless.')
$hl.Add(' *')
$hl.Add(' *  Regenerate:  tools\gen_filelist.ps1   (or run setup.bat)')
$hl.Add(' * ========================================================================== */')
$hl.Add('')
$hl.Add('#ifndef CODE_HEADERLIST_H')
$hl.Add('#define CODE_HEADERLIST_H')
$hl.Add('')
$hl.Add('/* Fallback for compilers without __has_include (very old ones).')
$hl.Add(' * Every real toolchain used here (GCC 10 / MSVC 2017+) has it. */')
$hl.Add('#ifndef __has_include')
$hl.Add('#  define __has_include(x) 0')
$hl.Add('#endif')
$hl.Add('')

if ($hFiles.Count -eq 0) {
    $hl.Add('/* no .h files under code\ yet */')
}
else {
    foreach ($f in $hFiles) {
        $rel = Get-RelPath $f.FullName $CodeDir
        $hl.Add('#if __has_include("../code/' + $rel + '")')
        $hl.Add('#  include "../code/' + $rel + '"')
        $hl.Add('#endif')
    }
}

$hl.Add('')
$hl.Add('#endif /* CODE_HEADERLIST_H */')

$hOutFile = Join-Path $EnvDir 'code_headerlist.h'
$hNewText = ($hl -join "`r`n") + "`r`n"

# --- write only when content actually changed (avoids needless rebuilds) ---
$newText = ($lines -join "`r`n") + "`r`n"
$changed = $true
if (Test-Path $OutFile) {
    $oldText = [System.IO.File]::ReadAllText($OutFile)
    if ($oldText -eq $newText) { $changed = $false }
}

# the header list is tracked separately: a change there must also force a rebuild
$hChanged = $true
if (Test-Path $hOutFile) {
    $hOldText = [System.IO.File]::ReadAllText($hOutFile)
    if ($hOldText -eq $hNewText) { $hChanged = $false }
}

if ($hChanged) {
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($hOutFile, $hNewText, $utf8Bom)
    Write-Host ("[gen_filelist] wrote env\code_headerlist.h ({0} header file(s))" -f $hFiles.Count) -ForegroundColor Cyan
}

if ($changed) {
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($OutFile, $newText, $utf8Bom)
    Write-Host ("[gen_filelist] wrote env\code_filelist.h ({0} source file(s))" -f $cFiles.Count) -ForegroundColor Cyan

    # --- force recompile of simu_env.c on the next Dev-C++ build ----------------
    #     The Makefile.win that Dev-C++ generates lists simu_env.o's
    #     dependencies as simu_env.c + simu_env.h only. code_filelist.h is
    #     #included BY simu_env.c but is NOT in that dependency list, so when
    #     the file list changes, Dev-C++ happily reuses the stale simu_env.o:
    #     user code added to code\ silently never gets linked in, and the
    #     symptom is confusing "undefined reference to image_process"-style
    #     linker errors. Deleting the stale object forces a real rebuild.
    #     (The VS project already handles this via its DSH_GenFileList target.)
    $devBuildObjs = @(
        (Join-Path $Root 'build\simu_env.o'),
        (Join-Path $Root 'build\simu_env.obj')
    )
    foreach ($obj in $devBuildObjs) {
        if (Test-Path $obj) {
            Remove-Item $obj -Force
            Write-Host ("[gen_filelist] deleted stale {0} (file list changed)" -f $obj) -ForegroundColor Yellow
        }
    }
}
else {
    Write-Host ("[gen_filelist] code_filelist.h up to date ({0} source file(s))" -f $cFiles.Count) -ForegroundColor Cyan
}

# A changed header list also has to invalidate the object files: disp_env.cpp
# includes code_headerlist.h, and that dependency is likewise not in any
# generated Makefile.
if ($hChanged) {
    foreach ($obj in @(
        (Join-Path $Root 'build\disp_env.o'),
        (Join-Path $Root 'build\disp_env.obj'))) {
        if (Test-Path $obj) {
            Remove-Item $obj -Force
            Write-Host ("[gen_filelist] deleted stale {0} (header list changed)" -f $obj) -ForegroundColor Yellow
        }
    }
}

# --- keep the Visual Studio project item list in sync -------------------------
#     so that new code\*.c / *.h files also appear in Solution Explorer.
#     (Compilation itself does not depend on this step -- that goes through
#      code_filelist.h above -- so a failure here is not fatal.)
$sync = Join-Path $PSScriptRoot 'sync_vs_items.ps1'
if (Test-Path $sync) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File $sync
}

# --- keep the Dev-C++ project units in sync -----------------------------------
#     same purpose as above, but for the .dev project tree. Only rewrites the
#     .dev when the unit list actually changes (see sync_dev_units.ps1).
$syncDev = Join-Path $PSScriptRoot 'sync_dev_units.ps1'
if (Test-Path $syncDev) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File $syncDev
}

exit 0
