@echo off
rem ============================================================================
rem  rebuild.bat -- scan code\ and force a full rebuild
rem ----------------------------------------------------------------------------
rem  WHY THIS EXISTS
rem    New files added under code\ are picked up automatically through
rem    env\code_filelist.h. That header is generated by tools\gen_filelist.ps1.
rem
rem    The VS project regenerates it on every build (see the DSH_GenFileList
rem    target in VS\visual_simu.vcxproj), so pressing F5 in Visual Studio
rem    always sees new files.
rem
rem    Dev-C++ has NO pre-build step, so pressing F11 can NOT regenerate the
rem    list by itself. If you just added a new .c under code\ and press F11,
rem    you get confusing "undefined reference to ..." linker errors.
rem
rem    Run this script once after adding/removing/renaming files under code\,
rem    then press F11 as usual. (It also works for the command-line builds.)
rem
rem  WHAT IT DOES
rem    1. rescans code\ and regenerates env\code_filelist.h
rem       (this also syncs the VS project items and the Dev-C++ unit list)
rem    2. deletes the stale object files in build\, so the next build really
rem       recompiles simu_env.c instead of quietly reusing an old .o
rem
rem  USAGE
rem    tools\rebuild.bat
rem    (then press F11 in Dev-C++, or F5 in Visual Studio)
rem
rem  NOTE: ASCII-only on purpose. .bat files are read as ANSI (codepage 936)
rem        on Chinese Windows, so non-ASCII text here would garble the parser.
rem ============================================================================
@echo off
setlocal
cd /d "%~dp0.."
set "ROOT=%CD%"

echo ============================================================
echo   Rescanning code\ and forcing a full rebuild
echo ============================================================
echo.

echo [1/2] regenerating env\code_filelist.h ...
powershell -NoProfile -ExecutionPolicy Bypass -File "%ROOT%\tools\gen_filelist.ps1"
if errorlevel 1 (
    echo.
    echo       [FAILED] could not regenerate code_filelist.h
    echo       Check that PowerShell is allowed to run scripts, then retry.
    goto :end
)
echo.

echo [2/2] removing stale object files ...
if exist "%ROOT%\build\*.o" (
    del /q "%ROOT%\build\*.o"
    echo       removed build\*.o
) else (
    echo       no stale .o files in build\
)
rem MSVC objects live under VS\x64\<Config>\ ; if one is left over from before
rem the file list changed, the next VS build can reuse it and miss new files.
if exist "%ROOT%\VS\x64\Debug\simu_env.obj" (
    del /q "%ROOT%\VS\x64\Debug\simu_env.obj"
    echo       removed VS\x64\Debug\simu_env.obj
)
if exist "%ROOT%\VS\x64\Release\simu_env.obj" (
    del /q "%ROOT%\VS\x64\Release\simu_env.obj"
    echo       removed VS\x64\Release\simu_env.obj
)
echo.

echo ============================================================
echo   Done. Now build as usual:
echo     * Dev-C++      : open the .dev file, press F11
echo     * Visual Studio: open VS\visual_simu.vcxproj, press F5
echo     * command line : tools\build_dev.bat  /  tools\build_vs.bat
echo ============================================================

:end
echo.
pause
endlocal
exit /b 0
